# Generated by Django 6.0.5 on 2026-05-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipts/deposits/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='expense',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipts/expenses/%Y/%m/'),
        ),
    ]
